# Data Mining Individual Project

BY CHEN Dongna 1730026004

In [1]:
import pandas as pd
import numpy as np
import operator
import random
import math
import csv
train = pd.read_csv('Dataset.csv')
train.head()

   A  B  C  D  E  F  G  H  I  Class
0  1 -1  1 -1 -1  1  1  1  0      0
1 -1 -1 -1 -1 -1  0  1  1  1      1
2  1 -1  0  0 -1  0 -1  1  0      1
3  1  0  1 -1 -1  0  1  1  0      0
4 -1 -1  1 -1  0  0 -1  1  0      1

In [2]:
def loadDataset(split, trainingSet=[], testSet=[]):
    with open("Dataset.csv", "r") as f:
        reader = csv.reader(f)
        dataset = [row for row in reader]
        dataset.pop(0)
    
        for x in range(len(dataset)-1):
            for y in range(9):
                dataset[x][y] = float(dataset[x][y])
                if random.random() < split:
                    trainingSet.append(dataset[x])
                else:
                    testSet.append(dataset[x])
    
    return trainingSet, testSet

In [3]:
trainingSet = []
testSet = []
loadDataset(0.67, trainingSet, testSet)
pd.DataFrame(testSet).head()

     0    1    2    3    4    5    6    7    8  9
0  1.0 -1.0  1.0 -1.0 -1.0  1.0  1.0  1.0  0.0  0
1  1.0 -1.0  1.0 -1.0 -1.0  1.0  1.0  1.0  0.0  0
2  1.0 -1.0  1.0 -1.0 -1.0  1.0  1.0  1.0  0.0  0
3  1.0 -1.0  1.0 -1.0 -1.0  1.0  1.0  1.0  0.0  0
4 -1.0 -1.0 -1.0 -1.0 -1.0  0.0  1.0  1.0  1.0  1

## KNN

In [4]:
def euclideanDistance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow((int(instance1[x]) - int(instance2[x])), 2)
    return math.sqrt(distance)

In [5]:
def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance) - 1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors

In [6]:
def getResponse(neighbors):
    classVotes = {}
    for x in range(len(neighbors)):
        response = neighbors[x][-1]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1), reverse=True)
    return sortedVotes[0][0]

In [7]:
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(0, len(testSet)):
        if testSet[x][-1] == predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [8]:
def knntest():
    trainingSet = []
    testSet = []
    loadDataset(0.67, trainingSet, testSet)
    
    predictions = []
    k = 5
    for x in range(len(testSet)):
        neighbors = getNeighbors(trainingSet, testSet[x], k)
        result = getResponse(neighbors)
        predictions.append(result)
        
    accuracy = getAccuracy(testSet, predictions)
    print('Accuracy:' + repr(accuracy) + '%')

In [9]:
knntest()

Accuracy:95.42796384901648%

### Prediction of Test Set

In [18]:
test = []
with open("test.csv", "r") as f:
    reader = csv.reader(f)
    dataset = [row for row in reader]
    dataset.pop(0)
    
    for x in range(len(dataset)-1):
        for y in range(1):
            dataset[x][y] = float(dataset[x][y])
            test.append(dataset[x])

In [19]:
predictions = []
k = 5

for x in range(len(test)):
    neighbors = getNeighbors(trainingSet, test[x], k)
    result = getResponse(neighbors)
    predictions.append(result)

print(predictions, end = "")

['-1', '1', '-1', '1', '1', '-1', '-1', '1', '-1', '-1', '0', '-1', '0', '-1', '-1', '-1', '-1', '1', '-1', '-1', '-1', '1', '1', '-1', '-1', '-1', '1', '-1', '1', '-1', '-1', '1', '1', '-1', '0', '-1', '-1', '0', '0', '-1', '0', '1', '1', '-1', '-1', '1', '-1', '0', '-1', '0', '0', '1', '-1', '1', '1', '-1', '-1', '-1', '-1', '-1', '-1', '-1', '1', '1', '-1', '-1', '1', '1', '-1', '1', '1', '-1', '-1', '0', '1', '1', '-1', '-1', '-1', '-1', '1', '-1', '1', '1', '1', '1', '-1', '1', '-1', '1', '-1', '1', '-1', '-1', '-1', '1', '-1', '1', '-1']

In [20]:
result = pd.DataFrame(columns = ['class'], data = predictions)
result.to_csv('./result.csv')

In [21]:
pd.DataFrame(test)

      0   1   2   3   4   5   6   7  8 9
0   1.0   0   1   1   1   0   0  -1  0
1   0.0  -1   0   0   1   0   0   1  0
2   1.0  -1   0   1   1   0   1   1  0
3  -1.0  -1   1  -1  -1   0  -1  -1  0
4   1.0  -1   0   0   0  -1   1   1  0
5   1.0   0   1   0  -1  -1  -1   1  1
6   1.0   0   1   1   0  -1  -1   1  1
7  -1.0  -1  -1  -1  -1   0   1   1  0
8  -1.0   1   1   1   1  -1   0   1  1
9   1.0   0   0   1   1   1   0  -1  0
10  1.0   0   1  -1  -1  -1   1   1  0
11  1.0   1   1   1   0   1   1  -1  0
12 -1.0  -1   1  -1   1   1  -1  -1  0
13  1.0   0   1   0  -1  -1   0   1  0
14  1.0   0   1   1   1   0   0  -1  0
15  1.0   1   1  -1   1   0  -1   1  0
16  1.0   0   1   0  -1  -1   1   1  0
17 -1.0  -1  -1  -1  -1   0  -1   1  0
18  1.0   1   1   1   1  -1   0   1  0
19  1.0   0   1   1   0  -1   0   1  0
20  1.0   0   1   1   1  -1   0   1  0
21 -1.0   0  -1  -1  -1   0  -1  -1  0
22  0.0   0  -1   0   1   1   1  -1  0
23  1.0   0   1  -1   1   1   0  -1  0
24  1.0  -1   0   1   0   0  -1  -1  0
25 -1.0   0   1   0  -1   0   0   1  0
26 -1.0  -1   1  -1  -1   0   0   1  0
27  1.0   0   1  -1   1  -1   1   1  1
28  1.0  -1   0   1   1  -1  -1   1  1
29  1.0   0   1   1   1  -1   0   1  1
..  ...  ..  ..  ..  ..  ..  ..  .. .. ..
69 -1.0  -1   1  -1  -1   1  -1  -1  0
70  0.0  -1  -1   0   1   0   0   1  0
71  1.0   0  -1   1   1  -1   0   1  0
72  1.0   0   1   1   1   1   1  -1  0
73 -1.0   0   0   0  -1  -1  -1   1  0
74  1.0  -1   0  -1  -1   1   0  -1  0
75 -1.0   0   1  -1  -1   1  -1  -1  0
76  0.0  -1   1   0   0  -1  -1   1  0
77  1.0   1  -1   1   1  -1   1   1  0
78  1.0  -1   1   1   1   1   1  -1  0
79  1.0   0   1  -1   1   0   1   1  1
80  0.0   0  -1   0   0   1   1  -1  0
81  1.0   0  -1   0  -1   1   0  -1  0
82  0.0  -1   1   0   1   1  -1  -1  0
83 -1.0  -1   0  -1  -1   0   0  -1  0
84 -1.0   0   1   0  -1   1  -1  -1  0
85  0.0   0  -1   0   0   1   0  -1  0
86  1.0   0   1   0  -1   0   1   1  0
87 -1.0   0  -1  -1   1   1  -1   1  0
88  1.0   0   1   0  -1   0   0   1  0
89 -1.0   0   1  -1  -1   1   0   1  0
90  1.0   1  -1   1   1   1   1  -1  0
91  0.0   0   0   0   1   0   0  -1  0
92 -1.0   0   1  -1   1   0  -1   1  0
93  1.0   1   0   0  -1  -1  -1   1  0
94  1.0   0   1   1   1  -1   0   1  0
95 -1.0  -1  -1  -1  -1  -1   0   1  0
96 -1.0   0   1   0  -1   0   0   1  0
97 -1.0   0  -1  -1  -1   0  -1  -1  0
98  0.0   0   1   0   0   0  -1   1  0

[99 rows x 10 columns]